### ISSUE TITLE
User

### ISSUE THREAD

**Issue by 89636443592** [MrSokol/CDR_Avaya#1]
Добрый день.
Не могли бы Вы подсказать, как Вашей разработкой пользоваться.
У нас Orange Pi H3, Nano Pi H3 (ARM Cortex A7).
С Линуксом работать стали совсем недавно.
Пользуемся netcat, но это не совсем удобно.
Можно ли с Вами связаться по электронной почте?
"Личку" на ГитХабе отыскать не могу.
Спасибо.

**Comment by MrSokol** [comment]
Добрый день!
Почта sokol@binhex.ru
